name: Mon workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Listing files
        run: ls -al
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.25.1

